coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
    patch:
      default:
        target: auto
        threshold: 10%
comment:
  layout: 'diff, flags, files'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
ignore:
  - 'apps'
  - 'packages/di'
  - 'packages/db'
  - '__tests__/coverage'
  - ./*.mjs
  - ./*.ts
  - packages/application/src/entities/*.ts
  - packages/infrastructure/src/repositories/*.ts
  - packages/infrastructure/src/services/*.ts